image: $CI_REGISTRY/docker/debian/maven:3.6.1_jdk8-jre_ci

# Include Global Configurations
include:
  - project: 'api-server/gitlab-ci-scripts'
    ref: v1.7
    file: '.global-configuration.yml'

variables:
  BASE_URL:   ""

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean compile
  only:
    - /^feature.*$/
    - develop

sonarqube:
  stage: test
  script:
    - git clone "$BASE_URL/api-server/gitlab-ci-scripts.git" targomo-config
    - cp targomo-config/mvn/settings.xml settings.xml
    - mvn --settings settings.xml verify sonar:sonar
      -Dsonar.host.url=$SONARQUBE_URL
      -Dsonar.login=$SONARQUBE_TOKEN
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.branch.target=develop
    - cat target/site/jacoco-ut/index.html
  only:
    - /^feature.*$/
    - develop

deploy_maven:
  stage: deploy
  script:
    - mvn -DperformRelease=true deploy
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - target/*.jar
  when: manual
  only:
    - master

deploy_nexus:
  stage: deploy
  script:
    - mvn -Dmaven.test.skip=true deploy
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - target/*.jar
  when: manual
  only:
    - /^feature.*$/
    - /^release.*$/
    - develop

# ----------------------------------------------------------------------------------------------------

.auto_devops: &auto_devops |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x


before_script:
  - *auto_devops
  - export BASE_URL=$(echo $CI_REPOSITORY_URL | sed "s,\/*$CI_PROJECT_PATH.*,,")
